name: Release

on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: npm
      - name: Install
        run: npm ci
      - name: Compile
        run: npm run compile
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - name: Test binaries
        run: npm run test:binaries
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/valetudo-helper-miioota.exe
            build/valetudo-helper-miioota-amd64
            build/valetudo-helper-miioota-armv7
            build/valetudo-helper-miioota-mac-arm64
